services:
  - type: web
    name: chatwoot
    env: docker
    plan: free
    branch: main
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: FRONTEND_URL
        value: https://tu-subdominio.onrender.com
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: chatwoot-redis
          property: connectionString
      - key: POSTGRES_HOST
        fromDatabase:
          name: chatwoot-db
          property: host
      - key: POSTGRES_USERNAME
        fromDatabase:
          name: chatwoot-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: chatwoot-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: chatwoot-db
          property: database

  - type: redis
    name: chatwoot-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all connections from Render internal network

databases:
  - name: chatwoot-db
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all connections from Render internal network
